name: contini_statisticini
description: "An application for taking track of everything you want through custom Counters."


publish_to: 'none' 


version: 1.0.1+1

environment:
  sdk: ^3.5.4



dependencies:
  intl: ^0.18.0
  flutter:
    sdk: flutter
  hive: ^2.2.0
  hive_flutter: ^1.1.0
  uuid: ^4.4.2

  
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

  
  
  flutter_lints: ^5.0.0





flutter:

  uses-material-design: true
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf